# Generated by Django 5.0.2 on 2024-02-24 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autoturargoh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='media/auto')),
                ('model', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('background', models.ImageField(upload_to='media/auto')),
                ('mator', models.CharField(max_length=100)),
                ('benzin', models.CharField(max_length=100)),
                ('uzatma', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Buyurtma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background', models.ImageField(upload_to='media/buyur')),
            ],
        ),
    ]
