# Generated by Django 5.0.2 on 2024-02-24 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ijara', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Autoturargoh',
            new_name='Auto',
        ),
        migrations.RenameModel(
            old_name='Buyurtma',
            new_name='Buyur',
        ),
    ]
